name: Generate Contribution Snake

on:
  schedule:
    # Runs automatically every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Karthikeyan-Ravichandran22
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?color_snake=#22D3EE&color_dots=#2d3343,#108981,#089182,#7C3AED,#A78BFA

      - name: Push Snake SVGs to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
